name: salami_cli
description: A Salami Command Line Interface for Dart created by DevTalens
version: 0.0.1-dev.4
homepage: https://github.com/HeyDevTalents

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.3.1
  glob: ^2.1.0
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.26 <0.1.0-dev.27"
  mason_logger: ">=0.1.0-dev.13 <0.1.0-dev.14"
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.2
  universal_io: ^2.0.4
  usage: ^4.1.0
  very_good_analysis: ^3.0.1
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.21.4

executables:
  salami:
